name: Deploy DotNet project to Azure Function App


on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: unit-test-function
  AZURE_WEBAPP_PACKAGE_PATH: "./utei-backend/UTEI"
  MONGODB_CONNECTION: ${{ vars.MONGODB_CONNECTIONSTRING }}
  DATABASE_NAME: ${{ vars.DATABASE_NAME }}
  OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
  EMAIL: ${{ vars.UTEI_MAILER_EMAIL }}
  EMAIL_PASSWORD: ${{ vars.UTEI_MAILER_PASSWORD }}
  ISSUER_SIGNING_KEY: ${{ vars.ISSUER_SIGNING_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore
        run: dotnet restore ./utei-backend/UTEI.sln
        
      - name: Build
        run: dotnet build ./utei-backend/UTEI.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./utei-backend/UTEI.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          publish-profile: ${{ secrets.UTEI_BACKEND_SECRET}}